### ISSUE TITLE
WX-3.0 must be built with "-DNDEBUG"

### ISSUE THREAD

**Issue by onlyjob** [wxLauncher/wxlauncher#117]
With WX-3.0 wxLauncher must be built with "-DNDEBUG" (which was default with WX-2.8).

When built without "-DNDEBUG" wxlauncher segfaults on second start when `~/.wxlauncher/global.ini` exists:

~~~~
ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxArgNormalizer /usr/include/wx-3.0/wx/strvararg.h:456
[2] wxLauncher::OnInit() /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:219
[3] wxEntry(int&, wchar_t**)
[4] main /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:50
[5] __libc_start_main
[6] _start
~~~~

It is very counter-intuitive that is necessary to build with "-DNDEBUG" on WX-3.0 and it is not mentioned anywhere.
Perhaps build system should be modified to handle NDEBUG build flag automatically?

**Comment by IssMneur** [comment]
23d96d3 should resolve this issue.

**Comment by onlyjob** [comment]
No the issue is still there. I applied 23d96d3, built on Debian/amd64 & WX-3.0 without "-DNDEBUG" and got the following crash:

~~~~
ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxArgNormalizer /usr/include/wx-3.0/wx/strvararg.h:456
[2] ~ConvertedBuffer /usr/include/wx-3.0/wx/string.h:3490
[3] ~ConvertedBuffer /usr/include/wx-3.0/wx/string.h:3490
[4] MainWindow::MainWindow() /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/MainWindow.cpp:77
[5] wxLauncher::OnInit() /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:248
[6] wxEntry(int&, wchar_t**)
[7] main /mnt/tmpssd/src/wxlauncher/wxlauncher-release-0.9.5/code/wxLauncherApp.cpp:50
[8] __libc_start_main
[9] _start
~~~~

**Comment by IssMneur** [comment]
What do you have on line 77 of code/MainWindow.cpp?  I have:

`	this->mainTab->AddPage(new ModsPage(this->mainTab), _("Mods"), false);`

**Comment by onlyjob** [comment]
Same thing.

**Comment by IssMneur** [comment]
0.9.6 release resolves this issue.

**Comment by bosaap** [comment]
this still happens to me as of current git d56c6dee36f1e74f60597ca563e3d52a974a4d8d

wx 3.0.2 

ASSERT INFO:
./include/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxFileConfig::Parse(wxTextBuffer const&, bool)
[2] wxFileConfig::wxFileConfig(wxInputStream&, wxMBConv const&)
[3] ModList::ParseModIni(wxString const&, wxString const&, bool)
[4] ModList::ModList(wxWindow*, wxSize&, wxString)
[5] ModsPage::OnTCChanged(wxCommandEvent&)
[6] ModsPage::ModsPage(wxWindow*)
[7] MainWindow::MainWindow()
[8] wxLauncher::OnInit()
[9] wxAppConsoleBase::CallOnInit()
[10] wxEntry(int&, wchar_t**)
[11] main
[12] __libc_start_main
[13] _start /usr/src/glibc-2.20/csu/../sysdeps/x86_64/start.S:125
